<?php

namespace ContainerWJy4s8P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GGSRLrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._gGSRLr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._gGSRLr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', 'App\\Repository\\ParticipantRepository', 'getParticipantRepositoryService', true],
        ], [
            'doctrine' => '?',
            'repo' => 'App\\Repository\\ParticipantRepository',
        ]);
    }
}
