<?php

namespace ContainerWJy4s8P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rq_RA6BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rq.RA6B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rq.RA6B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'flashBag' => ['privates', 'session.flash_bag', 'getSession_FlashBagService', true],
            'repo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'doctrine' => '?',
            'flashBag' => '?',
            'repo' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
