<?php

namespace ContainerWJy4s8P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CyFA_QxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CyFA.Qx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CyFA.Qx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'repository' => ['privates', 'App\\Repository\\ParticipantRepository', 'getParticipantRepositoryService', true],
        ], [
            'doctrine' => '?',
            'repository' => 'App\\Repository\\ParticipantRepository',
        ]);
    }
}
