<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWJy4s8P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWJy4s8P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWJy4s8P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWJy4s8P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWJy4s8P\App_KernelDevDebugContainer([
    'container.build_hash' => 'WJy4s8P',
    'container.build_id' => 'd4889584',
    'container.build_time' => 1708377443,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWJy4s8P');
